import localFont from "next/font/local";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";

// Import fonts with correct variable weights and paths
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata (you can expand with more SEO-related properties if needed)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout component definition
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
